
version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: 'jenkins'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_config:/var/jenkins_config

volumes:
  jenkins_data:
  jenkins_config:
